title: <p align="center"> Jacob Appia </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jacob-appia/">LinkedIn</a> |
  <a href="https://github.com/jacobappia">GitHub</a>
  </p>
  
  <p align="justify">
  I earned my Master's degree in Applied Statistics at Illinois State University.
  <br><br>
  I am currently a Data Scientist at WAfric Energy Solutions LLC where I conducted industry research and forecast demand.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-252265234-1 # Google Analytics tracking ID
